export const ADMIN_ROUTE = '/admin'
export const ADMIN_UPDATE = '/admin/update'
export const ADMIN_FINISHED_TABLE_ROUTE = '/admin/finished-table'
export const ADMIN_NOT_FINISHED_TABLE_ROUTE = '/admin/not-finished-table'
export const ADMIN_SETTINGS_ROUTE = '/admin/settings'

export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const FAVOURITE_ROUTE = '/favourite'
export const ABOUT_ROUTE = '/about'
export const CONTACT_ROUTE = '/contact'
export const DEVICE_ROUTE = '/device'

export const PHONES_CATEGORY_ROUTE = '/category/phones'
export const TABLETS_CATEGORY_ROUTE = '/category/tablets'
export const WATCHES_CATEGORY_ROUTE = '/category/watches'
export const COMPUTERS_CATEGORY_ROUTE = '/category/computers'
export const ACCESSORIES_CATEGORY_ROUTE = '/category/accessories'
export const CAMERAS_CATEGORY_ROUTE = '/category/cameras'
export const EQUIPMENTS_CATEGORY_ROUTE = '/category/equipments'